// default package
// Generated Jan 7, 2022, 7:42:05 PM by Hibernate Tools 5.5.7.Final
package com.fran.gestionstarwars.entity;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;



/**
 * People generated by hbm2java
 * @author Francisco David Manzanedo.
 */
@Entity
@Table(name = "people")
public class People implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "codigo", unique = true, nullable  = false)
	private int codigo;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "homeworld")
	private Planets planets;
	private String name;
	@Column(name = "birth_year")
	private String birthYear;
	@Column(name = "eye_color")
	private String eyeColor;
	private String gender;
	@Column(name = "hair_color")
	private String hairColor;
	private String height;
	private String mass;
	@Column(name = "skin_color")
	private String skinColor;
	private String created;
	private String edited;
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "starships_people", 
		joinColumns = { @JoinColumn(name = "codigo_people") }, 
		inverseJoinColumns = { @JoinColumn(name = "codigo_starship") })
	private Set<Starships> starships = new HashSet<Starships>();
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "species_people", 
		joinColumns = { @JoinColumn(name = "codigo_people") }, 
		inverseJoinColumns = { @JoinColumn(name = "codigo_specie") })
	private Set<Species> species = new HashSet<Species>();
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "vehicles_people", 
		joinColumns = { @JoinColumn(name = "codigo_people") }, 
		inverseJoinColumns = { @JoinColumn(name = "codigo_vehicle") })
	private Set<Vehicles> vehicles = new HashSet<Vehicles>();
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "films_people", 
		joinColumns = { @JoinColumn(name = "codigo_people") }, 
		inverseJoinColumns = { @JoinColumn(name = "codigo_film") })
	private Set<Films> films = new HashSet<Films>();

	public People() {
	}

	public People(int codigo) {
		this.codigo = codigo;
	}

	public People(int codigo, Planets planets, String name, String birthYear, String eyeColor, String gender,
			String hairColor, String height, String mass, String skinColor, String created, String edited,
			Set<Starships> starships, Set<Species> species, Set<Vehicles> vehicles, Set<Films> films) {
		this.codigo = codigo;
		this.planets = planets;
		this.name = name;
		this.birthYear = birthYear;
		this.eyeColor = eyeColor;
		this.gender = gender;
		this.hairColor = hairColor;
		this.height = height;
		this.mass = mass;
		this.skinColor = skinColor;
		this.created = created;
		this.edited = edited;
		this.starships = starships;
		this.species = species;
		this.vehicles = vehicles;
		this.films = films;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	
	public Planets getPlanets() {
		return this.planets;
	}

	public void setPlanets(Planets planets) {
		this.planets = planets;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getBirthYear() {
		return this.birthYear;
	}

	public void setBirthYear(String birthYear) {
		this.birthYear = birthYear;
	}

	public String getEyeColor() {
		return this.eyeColor;
	}

	public void setEyeColor(String eyeColor) {
		this.eyeColor = eyeColor;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getHairColor() {
		return this.hairColor;
	}

	public void setHairColor(String hairColor) {
		this.hairColor = hairColor;
	}

	public String getHeight() {
		return this.height;
	}

	public void setHeight(String height) {
		this.height = height;
	}

	public String getMass() {
		return this.mass;
	}

	public void setMass(String mass) {
		this.mass = mass;
	}

	public String getSkinColor() {
		return this.skinColor;
	}

	public void setSkinColor(String skinColor) {
		this.skinColor = skinColor;
	}

	public String getCreated() {
		return this.created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	public String getEdited() {
		return this.edited;
	}

	public void setEdited(String edited) {
		this.edited = edited;
	}

	
	public Set<Starships> getStarships() {
		return this.starships;
	}

	public void setStarships(Set<Starships> starships) {
		this.starships = starships;
	}
	
	
	public Set<Species> getSpecies() {
		return this.species;
	}

	public void setSpecies(Set<Species> species) {
		this.species = species;
	}
	
	public Set<Vehicles> getVehicles() {
		return this.vehicles;
	}

	public void setVehicles(Set<Vehicles> vehicles) {
		this.vehicles = vehicles;
	}
	
	public Set<Films> getFilms() {
		return this.films;
	}

	public void setFilms(Set<Films> films) {
		this.films = films;
	}
}
